export const keywords: { [category: string]: string[] } = {
  "phishing": [
    "verify your account",
    "urgent action required",
    "suspended account",
    "click here immediately",
    "confirm your identity",
    "unusual activity",
    "security alert",
    "verify payment",
    "account will be closed",
    "update your information",
    "confirm your password",
    "validate your account",
    "reactivate your account",
    "your account has been locked",
    "suspicious login attempt",
    "unauthorized access detected",
    "verify your email address",
    "restore access now",
    "billing information expired",
    "payment failed"
  ],
  "spam": [
    "limited time offer",
    "act now",
    "winner",
    "congratulations",
    "free money",
    "no credit check",
    "earn money fast",
    "work from home",
    "make money online",
    "risk-free",
    "no hidden fees",
    "guaranteed approval",
    "double your income",
    "lose weight fast",
    "miracle cure",
    "get rich quick",
    "billion dollars",
    "instant access",
    "order now",
    "call now",
    "for only",
    "100% free",
    "amazing offer",
    "once in a lifetime"
  ],
  "malware": [
    "download attachment",
    "enable macros",
    "run this file",
    "install software",
    "execute",
    ".exe",
    ".scr",
    ".bat",
    ".cmd",
    "click to install",
    "update required",
    "software update available",
    "install now",
    "download now",
    "open attached file",
    "view document",
    "enable content",
    "activate windows",
    "antivirus expired",
    "system scan required"
  ],
  "socialEngineering": [
    "ceo request",
    "urgent wire transfer",
    "gift card",
    "confidential",
    "do not share",
    "password reset",
    "immediate assistance",
    "boss needs",
    "company policy",
    "hr department",
    "payroll update",
    "direct deposit",
    "tax refund",
    "irs notice",
    "legal action",
    "court summons",
    "warrant issued",
    "prize notification",
    "inheritance",
    "beneficiary",
    "secret",
    "discreet",
    "urgent help needed",
    "family emergency"
  ]
}